In [1]:
import numpy as np

# 1.Import numpy as np and see the version

In [123]:
np.__version__

'1.18.1'

# 2.How to create a 1D array?

In [125]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#How to create a 1D array? another method
ar1 = np.arange(10)
ar

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 3.How to create a boolean array?
#Q. Create a 3×3 numpy array of all True’s

In [127]:
bo = np.full((3,3),True)
bo

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
bo.dtype

dtype('bool')

In [156]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# 4.How to extract items that satisfy a given condition from 1D array?
#Q. Extract all even numbers from arr
#Q. Extract all odd numbers from arr

In [129]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
ar[ar%2==0] # getting even numbers from above 1D array

array([0, 2, 4, 6, 8])

In [16]:
ar[ar%2==1]  # getting odd numbers from above 1D array

array([1, 3, 5, 7, 9])

# 5.How to replace items that satisfy a condition with another value in numpy array?
#Q. Replace all odd numbers in ar with -1

In [130]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
ar[ar%2==1]=-1
ar

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [28]:
ar

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6.How to replace items that satisfy a condition without affecting the original array?
#Q. Replace all odd numbers in arr with -1 without changing ar1

In [132]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
out = np.where(ar1 % 2 == 1, -1, ar1)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
hi = np.where(ar1%2==0,'love',ar1)
hi

array(['love', '1', 'love', '3', 'love', '5', 'love', '7', 'love', '9'],
      dtype='<U11')

In [30]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
ar1.shape

(10,)

# 7.How to Reshape?
#Q. Convert a 1D array to a 2D array with 2 rows

In [134]:
ar1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# 8.How to stack two arrays vertically?
#Q. Stack arrays a and b vertically

In [114]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(2, 10).reshape(2,-1)

In [115]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [116]:
b

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [117]:
# Method 1:
np.concatenate([a, b], axis=0)  # means to merge two things together vertically

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [118]:
# Method 2:
np.vstack([a, b])     # means to merge two things together vertically

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [119]:
# Method 3:
np.r_[a, b]     # means to merge two things together vertically

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

# 9.How to stack two arrays horizontally?
#Q. Stack arrays a and b horizontally?

In [122]:
#Method 1:
np.concatenate([a,b],axis=1)  # means to merge two things together horizontally

array([[0, 1, 2, 3, 4, 2, 2, 2, 2, 2],
       [5, 6, 7, 8, 9, 2, 2, 2, 2, 2]])

In [53]:
#Method 2:
np.hstack([a,b])     # means to merge two things together horizontally

array([[0, 1, 2, 3, 4, 2, 2, 2, 2, 2],
       [5, 6, 7, 8, 9, 2, 2, 2, 2, 2]])

In [54]:
np.stack([a,b])

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])

In [55]:
#Method 3: 
np.c_[a,b]     # means to merge two things together horizontally

array([[0, 1, 2, 3, 4, 2, 2, 2, 2, 2],
       [5, 6, 7, 8, 9, 2, 2, 2, 2, 2]])

# 10. How to generate custom sequences in numpy without hardcoding?
#Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [109]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [59]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11. How to get the common items between two python numpy arrays?
#Q. Get the common items between a and b

In [64]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [65]:
np.intersect1d(a,b)

array([2, 4])

# 12. How to remove from one array those items that exist in another?
#Q. From array a remove all items present in array b

In [71]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [72]:
## From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# 13. How to get the positions where elements of two arrays match?
#Q. Get the positions where elements of a and b match

In [73]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [74]:
# positions matching
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# 14. How to extract all numbers between a given range from a numpy array?
#Q. Get all items between 5 and 10 from a.

In [76]:
a = np.array([2, 6, 1, 9, 10, 3, 27,4,5,25,100,15,23,0,5,19,8])
a

array([  2,   6,   1,   9,  10,   3,  27,   4,   5,  25, 100,  15,  23,
         0,   5,  19,   8])

In [84]:
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10,  5,  5,  8])

In [85]:
# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10,  5,  5,  8])

In [86]:
# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10,  5,  5,  8])

# 15. How to make a python function that handles scalars to work on numpy arrays?
#Q. Convert the function maxx that works on two scalars, to work on two arrays.

In [88]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [94]:
# def maxx(x, y):
#     """Get the maximum of two items"""
#     if x >= y:
#         return x
#     else:
#         return y

pair_max = np.vectorize(maxx, otypes=[int])

# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

# 16. How to swap two columns in a 2d numpy array?
#Q. Swap columns 1 and 2 in the array arr.

In [96]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
arr[:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
arr[:,[1,2,0]]

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

# 17. How to swap two rows in a 2d numpy array?
Q. Swap rows 1 and 2 in the array arr:

In [102]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18. How to reverse the rows of a 2D array?
#Q. Reverse the rows of a 2D array arr.

In [135]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [138]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 19. How to reverse the columns of a 2D array?
#Q. Reverse the columns of a 2D array arr

In [139]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [142]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 20. How to create a 2D array containing random floats between 5 and 10?
#Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [146]:
# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[5.76902051 7.70086329 6.23721321]
 [5.30286203 7.18465336 5.39980221]
 [5.54170903 5.01083811 6.90892462]
 [9.67790085 5.08084582 8.86345518]
 [7.65838131 8.15430195 6.68135648]]


In [147]:
# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[8.63512545 8.64031021 7.69835746]
 [9.76555459 9.71175487 6.2854261 ]
 [8.98914118 7.82748455 9.31945917]
 [7.04619881 9.15167058 5.03010141]
 [8.84166769 9.42381099 9.83672042]]


# 21. How to print only 3 decimal places in python numpy array?
#Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [155]:
# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
rand_arr

array([[0.168, 0.008, 0.318],
       [0.193, 0.166, 0.312],
       [0.183, 0.542, 0.687],
       [0.466, 0.242, 0.05 ],
       [0.672, 0.536, 0.503]])